[project]
name = "jira-export-tasks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
    "pdfkit>=1.0.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "tabulate>=0.9.0",
]
